[project]
name = "crew-enterprise-mcp-server-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.4.1",
    "requests>=2.32.5",
]
